using Microsoft.AspNetCore.Mvc;
using TodoApp.Models;
using TodoApp.Services;

namespace TodoApp.Controllers;

/// <summary>
/// REST API for managing Todo items.
///
/// Graph labels generated by rn-token-optimizer:
///   - TodoController          → Controller     (name ends with "Controller")
///   - GetAll, GetById, …      → ApiEndpoint    (public methods + HTTP attributes)
///   - ITodoService            → INJECTS edge   (constructor DI)
///   - [HttpGet], [HttpPost]…  → route stored as HANDLES_ROUTE edge property
/// </summary>
[ApiController]
[Route("api/[controller]")]
public class TodoController : ControllerBase
{
    private readonly ITodoService _todoService;

    public TodoController(ITodoService todoService)
    {
        _todoService = todoService;
    }

    // ── GET /api/todo ──────────────────────────────────────────────────────────

    /// <summary>Returns a paged list of todos.</summary>
    [HttpGet]
    [ProducesResponseType(typeof(PagedResult<TodoDto>), StatusCodes.Status200OK)]
    public async Task<IActionResult> GetAll(
        [FromQuery] int   page            = 1,
        [FromQuery] int   pageSize        = 10,
        [FromQuery] bool? completedFilter = null)
    {
        var result = await _todoService.GetAllAsync(page, pageSize, completedFilter);
        return Ok(result);
    }

    // ── GET /api/todo/{id} ────────────────────────────────────────────────────

    /// <summary>Returns a single todo by ID.</summary>
    [HttpGet("{id:int}")]
    [ProducesResponseType(typeof(TodoDto), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> GetById([FromRoute] int id)
    {
        var todo = await _todoService.GetByIdAsync(id);
        return todo is null ? NotFound() : Ok(todo);
    }

    // ── POST /api/todo ─────────────────────────────────────────────────────────

    /// <summary>Creates a new todo.</summary>
    [HttpPost]
    [ProducesResponseType(typeof(TodoDto), StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<IActionResult> Create([FromBody] CreateTodoRequest request)
    {
        if (!ModelState.IsValid) return BadRequest(ModelState);

        var created = await _todoService.CreateAsync(request);
        return CreatedAtAction(nameof(GetById), new { id = created.Id }, created);
    }

    // ── PUT /api/todo/{id} ─────────────────────────────────────────────────────

    /// <summary>Replaces all fields of an existing todo.</summary>
    [HttpPut("{id:int}")]
    [ProducesResponseType(typeof(TodoDto), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> Update(
        [FromRoute] int               id,
        [FromBody]  UpdateTodoRequest request)
    {
        if (!ModelState.IsValid) return BadRequest(ModelState);

        var updated = await _todoService.UpdateAsync(id, request);
        return updated is null ? NotFound() : Ok(updated);
    }

    // ── DELETE /api/todo/{id} ──────────────────────────────────────────────────

    /// <summary>Permanently deletes a todo.</summary>
    [HttpDelete("{id:int}")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> Delete([FromRoute] int id)
    {
        var deleted = await _todoService.DeleteAsync(id);
        return deleted ? NoContent() : NotFound();
    }

    // ── PATCH /api/todo/{id}/complete ──────────────────────────────────────────

    /// <summary>Marks a todo as complete.</summary>
    [HttpPatch("{id:int}/complete")]
    [ProducesResponseType(typeof(TodoDto), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> MarkComplete([FromRoute] int id)
    {
        var result = await _todoService.MarkCompleteAsync(id);
        return result is null ? NotFound() : Ok(result);
    }

    // ── PATCH /api/todo/{id}/incomplete ───────────────────────────────────────

    /// <summary>Reopens a completed todo.</summary>
    [HttpPatch("{id:int}/incomplete")]
    [ProducesResponseType(typeof(TodoDto), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> MarkIncomplete([FromRoute] int id)
    {
        var result = await _todoService.MarkIncompleteAsync(id);
        return result is null ? NotFound() : Ok(result);
    }

    // ── GET /api/todo/by-priority/{priority} ───────────────────────────────────

    /// <summary>Returns all todos filtered by priority level.</summary>
    [HttpGet("by-priority/{priority}")]
    [ProducesResponseType(typeof(IReadOnlyList<TodoDto>), StatusCodes.Status200OK)]
    public async Task<IActionResult> GetByPriority([FromRoute] TodoPriority priority)
    {
        var items = await _todoService.GetByPriorityAsync(priority);
        return Ok(items);
    }
}
