using TodoApp.Data;
using TodoApp.Models;

namespace TodoApp.Repositories;

/// <summary>
/// In-memory repository implementation.
///
/// Graph labels generated by rn-token-optimizer:
///   - TodoRepository  → Repository  (name ends with "Repository")
///   - ITodoRepository → Interface   (via IMPLEMENTS edge)
///   - InMemoryDatabase is INJECTS edge (constructor DI)
/// </summary>
public class TodoRepository : ITodoRepository
{
    private readonly InMemoryDatabase _db;

    public TodoRepository(InMemoryDatabase db)
    {
        _db = db;
    }

    public Task<IReadOnlyList<Todo>> GetAllAsync(bool? completedFilter = null)
    {
        var all = _db.GetAll();

        IReadOnlyList<Todo> result = completedFilter.HasValue
            ? [.. all.Where(t => t.IsCompleted == completedFilter.Value)]
            : all;

        return Task.FromResult(result);
    }

    public Task<Todo?> GetByIdAsync(int id)
        => Task.FromResult(_db.FindById(id));

    public Task<Todo> AddAsync(Todo todo)
        => Task.FromResult(_db.Add(todo));

    public Task<Todo?> UpdateAsync(Todo todo)
    {
        var success = _db.Update(todo);
        return Task.FromResult(success ? todo : (Todo?)null);
    }

    public Task<bool> DeleteAsync(int id)
        => Task.FromResult(_db.Delete(id));

    public Task<int> CountAsync(bool? completedFilter = null)
    {
        var all = _db.GetAll();
        var count = completedFilter.HasValue
            ? all.Count(t => t.IsCompleted == completedFilter.Value)
            : all.Count;
        return Task.FromResult(count);
    }
}
