using Microsoft.Extensions.Logging;
using TodoApp.Models;
using TodoApp.Repositories;

namespace TodoApp.Services;

/// <summary>
/// Business logic layer.
///
/// Graph labels generated by rn-token-optimizer:
///   - TodoService      → Service     (name ends with "Service")
///   - ITodoService     → Interface   (IMPLEMENTS edge)
///   - ITodoRepository  → INJECTS edge (constructor DI)
///   - ILogger          skipped       (built-in type filter)
/// </summary>
public class TodoService : ITodoService
{
    private readonly ITodoRepository         _repository;
    private readonly ILogger<TodoService>    _logger;

    public TodoService(ITodoRepository repository, ILogger<TodoService> logger)
    {
        _repository = repository;
        _logger     = logger;
    }

    public async Task<PagedResult<TodoDto>> GetAllAsync(
        int page, int pageSize, bool? completedFilter = null)
    {
        var all   = await _repository.GetAllAsync(completedFilter);
        var total = await _repository.CountAsync(completedFilter);

        var paged = all
            .OrderByDescending(t => t.Priority)
            .ThenByDescending(t => t.CreatedAt)
            .Skip((page - 1) * pageSize)
            .Take(pageSize)
            .Select(TodoDto.FromEntity)
            .ToList();

        _logger.LogInformation("GetAllAsync: returned {Count} of {Total}", paged.Count, total);

        return new PagedResult<TodoDto>
        {
            Items      = paged,
            TotalCount = total,
            Page       = page,
            PageSize   = pageSize,
        };
    }

    public async Task<TodoDto?> GetByIdAsync(int id)
    {
        var todo = await _repository.GetByIdAsync(id);
        return todo is null ? null : TodoDto.FromEntity(todo);
    }

    public async Task<TodoDto> CreateAsync(CreateTodoRequest request)
    {
        var todo = new Todo
        {
            Title       = request.Title.Trim(),
            Description = request.Description.Trim(),
            Priority    = request.Priority,
        };

        var created = await _repository.AddAsync(todo);
        _logger.LogInformation("Created todo #{Id}: {Title}", created.Id, created.Title);
        return TodoDto.FromEntity(created);
    }

    public async Task<TodoDto?> UpdateAsync(int id, UpdateTodoRequest request)
    {
        var existing = await _repository.GetByIdAsync(id);
        if (existing is null) return null;

        existing.Title       = request.Title.Trim();
        existing.Description = request.Description.Trim();
        existing.Priority    = request.Priority;

        if (request.IsCompleted && !existing.IsCompleted)
            existing.CompletedAt = DateTime.UtcNow;
        else if (!request.IsCompleted)
            existing.CompletedAt = null;

        existing.IsCompleted = request.IsCompleted;

        var updated = await _repository.UpdateAsync(existing);
        return updated is null ? null : TodoDto.FromEntity(updated);
    }

    public async Task<bool> DeleteAsync(int id)
    {
        var deleted = await _repository.DeleteAsync(id);
        if (deleted) _logger.LogInformation("Deleted todo #{Id}", id);
        return deleted;
    }

    public async Task<TodoDto?> MarkCompleteAsync(int id)
    {
        var todo = await _repository.GetByIdAsync(id);
        if (todo is null) return null;

        todo.IsCompleted = true;
        todo.CompletedAt = DateTime.UtcNow;

        var updated = await _repository.UpdateAsync(todo);
        return updated is null ? null : TodoDto.FromEntity(updated);
    }

    public async Task<TodoDto?> MarkIncompleteAsync(int id)
    {
        var todo = await _repository.GetByIdAsync(id);
        if (todo is null) return null;

        todo.IsCompleted = false;
        todo.CompletedAt = null;

        var updated = await _repository.UpdateAsync(todo);
        return updated is null ? null : TodoDto.FromEntity(updated);
    }

    public async Task<IReadOnlyList<TodoDto>> GetByPriorityAsync(TodoPriority priority)
    {
        var all = await _repository.GetAllAsync();
        return all
            .Where(t => t.Priority == priority)
            .Select(TodoDto.FromEntity)
            .ToList();
    }
}
